version: 2

jobs:
    build:
        working_directory: ~/jfive-web-components
        docker:
            - image: circleci/node:8.1.2
        steps:
            - checkout
            - run:
                name: Install Bower dependencies
                command: sudo npm install -g bower && bower install
            - run:
                name: Install Electron dependencies
                command: sudo apt-get install xvfb && sudo apt-get install libgtk2.0-0 && sudo apt-get install libxtst6 && sudo apt-get install libXss1 && sudo apt-get install Libgconf-2-4 && sudo apt-get install libnss3 && sudo apt-get install libasound2
            - run: sudo npm test
